### PR TITLE
Update requirements.txt + MQTT client ID argument

### PR DESCRIPTION
**Pull request by jpeg2600**
added missing requirements + MQTT client ID argument

### CODE REVIEW

**Comment by fifieldt** [comment]
Hi and many thanks for the patch! requirements, client ID, float changes look good.

Could you comment more your needs for capturing text messages? Part of the reason I put this code online was to try and address some of the recent map privacy concerns, so am treading a conservative line :)

**Comment by jpeg2600** [comment]
Hi! Cool project, I'm having fun so far. I'll be using it for a localized MQTT server instance and displaying last messages will make it more fun and rewarding for experimentation. When I was experimenting with APRS on VHF, it was great to see my messages displayed on the map. As for privacy concerns, I don't think people should expect it when using no encryption or the default key. 

Maybe I can add an argument to turn the feature on? I was also thinking of not storing the messages when it was user to user but I didn't experiment with that so far. 

Cheers and greetings from Québec, Canada!

**Comment by fifieldt** [comment]
Thanks for the rapid reply! Fun is important :)

Yes, if you could add some way to default it off that would be great :)

**Comment by jpeg2600** [comment]
I rewrote a bit of the feature creation stuff to build dictionaries then json dump them as strings when the time comes instead of doing concats. That allowed me to manage the last message more easily.  

I couldn't test links or multipoints though :) 

Fun project, I played with your code all afternoon and now it's 10PM

**Review by fifieldt — APPROVED** [review]

**Comment by fifieldt** [comment]
Many thanks :)

**Pull request merged**
